name: Test compilation

on: [push, pull_request]

# Prevent parallel CI: Stop every workflow of a branch
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Try to restore opam cache
        id: opam-cache
        uses: actions/cache@v3
        with:
          path: "~/.opam"
          key: opam-${{ hashFiles('opam') }}

      - name: Install OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14

      - name: Install Coq and Iris
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam install . --deps-only -y

      - name: Build
        run: opam exec -- make ci

      - name: Build docs
        run: opam exec -- make html

      - name: Deploy docs (if main branch)
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ steps.get_branch.outputs.branch == 'main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          destination_dir: dev

      - name: Deploy docs (if non-main branch)
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ steps.get_branch.outputs.branch != 'main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          destination_dir: branch/${{ steps.get_branch.outputs.branch }}
