name: Test compilation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ build ]

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Try to restore opam cache
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: opam-${{ hashFiles('opam') }}

      - name: Install OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.07.1

      - run: opam repo add coq-released https://coq.inria.fr/opam/released
      - run: opam install . --deps-only -y

      - run: opam exec -- make -j $(nproc)
